config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  devise_for :users
  resources :users, :path => "mon_profil"
  
  devise_for :producers
  resources :producers, :path => "profil_producteur"
  
  resources :producers do
    put :favorite, on: :member
    member do
      delete :delete_image_attachment
    end
  end

  resources :contacts, only: [:new, :create]

  resources :comments
  resources :ratings

  namespace :admin do
    resources :producers, :comments, :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :ratings
  has_one_attached :avatar_user

  has_many :comments
  has_many :favorite_producers
  has_many :favorites, through: :favorite_producers, source: :producer

  validates :phone_number, if: :phone_number_nil?,
    length: { is: 10 },
    format: { with: /\d[0-9]\)*\z/ , message: "doit être au format : 0601020304 (pas d'espace)"}

  validates :first_name, :last_name, if: :names_nil?,
    length: { minimum: 1 }

  private

  def phone_number_nil?
    phone_number != nil
  end

  def names_nil?
    first_name != nil
    last_name != nil
  end


  ### Sending an email when a user is created
  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  # sending an email when a user is deleted
  before_destroy :goodbye_send
  def goodbye_send
    UserMailer.goodbye_email(self).deliver_now
  end

  before_destroy :goodbye_send
  def goodbye_send
    UserMailer.goodbye_email(self).deliver_now
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_current_user_showing?, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      flash[:notice] = 'Vous avez supprimé votre compte utilisateur. A bientôt !'
      redirect_to root_url
    else
      flash[:error] = 'Une erreur est survenue, nous vous invitons à nous contacter directement.'
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])
    avatar_user = params.dig(:user, :avatar_user)
    first_name = params.dig(:user, :first_name)
    last_name = params.dig(:user, :last_name)
    if avatar_user.nil? && first_name.nil?
      flash[:error] = 'Vous ne pouvez pas télécharger une image vide'
      redirect_to user_path(current_user.id)

    elsif @user.update(user_params)
      flash[:notice] = 'Vos informations ont été mises à jour !'
      redirect_to user_path(current_user.id)

    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def is_current_user_showing?
    unless current_user.id.to_s == params[:id].to_s
      flash[:error] = "Vous ne pouvez pas afficher un profil utilisateur qui n'est pas le vôtre !"
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :phone_number, :avatar_user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section id="fh5co-home" data-section="contact" style="background-image: url(&quot; https://cdn.pixabay.com/photo/2019/06/16/19/10/wheat-4278543_1280.jpg &quot;); background-position: 0px 0px; height: 200px" data-stellar-background-ratio="0.5">
  <div class="gradient"></div>
  <div class="container">
    <div class="text-wrap" style="height: 180px">
      <div class="text-inner">
        <div class="row text-center">
          <div class="col-md-8 col-md-offset-2">
            <h1 class="to-animate">Édition du profil</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="slant"></div>
</section>

<section id="fh5co-testimonials" data-section="connection" class='pt-5'>
  <div class="col-8 offset-2 col-sm-6 offset-sm-3 col-lg-4 offset-lg-4 to-animate text-center">
    <%= form_for(@user, as: current_user, url: user_path(current_user), html: { method: :put }) do |f| %>

      <div class="form-group text-left mb-4">
        <%= f.label :first_name, 'Prénom' %><br />
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="email" style='width: 41px'><i class="fas fa-address-card"></i></span>
          </div>
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" , placeholder:"Prénom", class:"form-control", style: 'text-transform: capitalize;'%>
        </div>
      </div>

      <div class="form-group text-left mb-4">
        <%= f.label :last_name, 'Nom de famille' %>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="email" style='width: 41px'><i class="far fa-address-card"></i></span>
          </div>
          <%= f.text_field :last_name, autocomplete: "last_name", placeholder:"NOM DE FAMILLE", class:"form-control", style: 'text-transform: uppercase;' %>
        </div>
      </div>

      <div class="form-group text-left mb-4">
        <%= f.label :phone_number, 'Numéro de téléphone' %>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="email" style='width: 41px'><i class="fas fa-mobile-alt"></i></span>
          </div>
          <%= f.text_field :phone_number, autocomplete: "phone_number ", maxlength: 10, placeholder:"0601020304", class:"form-control" %>
        </div>
      </div>

      <div class="actions mt-4">
        <%= f.submit "Mettre à jour", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>

    <div class="row justify-content-center mt-4 mb-5">
      <%= link_to "Retour", :back, class: 'mx-3' %>
    </div>

  </div>
</section>

app/views/users/show.html.erb
<section id="fh5co-home" data-section='profile-user' style="background-image: url(&quot; https://cdn.pixabay.com/photo/2019/06/16/19/10/wheat-4278543_1280.jpg &quot;); background-position: 0px 0px; height: 200px;" data-stellar-background-ratio="0.5">
  <div class="gradient"></div>
  <div class="container">
    <div class="text-wrap" style="height: 180px;">
      <div class="text-inner">
        <div class="row text-center">
          <div class="col-md-8 col-md-offset-2">
            <h1 class="to-animate">Mon profil</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="slant"></div>
</section>

<section id="fh5co-work" class='pt-5'>
  <div class='container'>

    <section id="information-editing" class='mt-5'>
      <% if user_signed_in? %>
        <div class="row my-3">
          <div class="col-md-6">
            <%= link_to "Modifier mes identifiants", edit_user_registration_path, class: "btn btn-primary btn-lg my-2" %>
          </div>
          <div class="col-md-5 text-center px-0 mx-3">
            <%= link_to "Modifier mes informations", edit_user_path(current_user), class: "btn btn-primary btn-lg w-100 my-2" %>
          </div>
        </div>
      <% end %>
    </section>


    <div class="row">
      <div class="col-md-6 text-center to-animate h-100 align-self-center mt-3" style='max-height: 400px;'>
        <% if @user.avatar_user.attached? %>
          <%= link_to image_tag(@user.avatar_user, alt: 'avatar_user', class:'img-responsive avatar to-animate'), @user.avatar_user, class:'fh5co-project-item image-popup to-animate' %>
        <% else %>
          <p class='font-italic box-avatar'>Il n'y a pas encore d'avatar lié à cet utilisateur</p>
        <% end %>
        <% if user_signed_in? %>
          <div class='text-left mb-3'>
          <%= form_with model: @user, local: true do |form| %>
              <div class='input-group'>
                <div class="input-group-prepend">
                  <%= form.submit "Ajouter", class:'btn btn-primary' %>
                </div>
                <div class="custom-file">
                  <%= form.file_field :avatar_user, id: 'avatar_user', accept: 'image/png,image/jpeg,image/gif', class:'custom-file-input' %>
                  <%= form.label :avatar_user, "Sélectionner une image...", class:'custom-file-label' %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 fh5co-contact-info to-animate h-100 mx-3 mt-3" id='user-producer-information'>
        <table class="table table-borderless text-white text-left my-2">
          <tbody>
            <tr>
              <td scope="col" style="width: 30%; overflow: hidden;"><i class="fas fa-address-card"></i></td>
              <td scope="col" style="width: 70%; overflow: hidden;">
                <% if @user.first_name.nil? || @user.last_name.nil? %>
                  <em>Non enregistré</em>
                <% else %>
                  <%= @user.first_name.capitalize %> <%= @user.last_name.upcase %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><i class="fas fa-phone-alt"></i></td>
              <td>
                <% if @user.phone_number.nil? %>
                  <span class='font-italic'>Non enregistré</span>
                <% else %>
                  <%= @user.phone_number %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><i class="fas fa-at"></i></td>
              <td><a href="mailto:<%= @user.email%>"><%= @user.email%></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="container px-0 my-5">
      <div class="text-center">
        <hr class='my-5 style-one'>
        <h2 class="text-white">Mes producteurs favoris !</h2>
      </div>
      <div class="col fh5co-contact-info">
        <table class="table text-light text-center table-hover table-borderless table-responsive">
          <thead>
            <tr class="border-bottom">
              <th scope="col" style="width: 20%; overflow: hidden;">Nom</th>
              <th scope="col" style="width: 20%; overflow: hidden;">Prénom</th>
              <th scope="col" style="width: 20%; overflow: hidden;">Téléphone</th>
              <th scope="col" style="width: 20%; overflow: hidden;">Email</th>
              <th scope="col" style="width: 10%; overflow: hidden;">Profil</th>
              <th scope="col" style="width: 10%; overflow: hidden;">Retirer</th>
            </tr>
          </thead>
          <tbody>
          <% current_user.favorites.each do |producer| %>
            <tr>
              <td class="py-2"><%= link_to producer.last_name, producer_path(producer.id) %></td>
              <td class="py-2"><%= link_to producer.first_name, producer_path(producer.id) %></td>
              <td class="py-2"><%= tel_to producer.phone_number, producer.phone_number %></td>
              <td class="py-2"><%= mail_to producer.email, producer.email %> </a></td>
              <td class="py-2"><%= link_to "Voir", producer_path(producer.id) %></td>
              <td class="py-2">
                <%= link_to favorite_producer_path(producer, type: "unfavorite-from-user-profile"), method: :put do %>
                  <span style="color: red;"><i class="fas fa-trash"></i></span>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</section>