config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  devise_for :users
  resources :users, :path => "mon_profil"
  
  devise_for :producers
  resources :producers, :path => "profil_producteur"
  
  resources :producers do
    put :favorite, on: :member
    member do
      delete :delete_image_attachment
    end
  end

  resources :contacts, only: [:new, :create]

  resources :comments
  resources :ratings

  namespace :admin do
    resources :producers, :comments, :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :join_table_product_category
	has_many :producers, through: :join_table_product_category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :producer
  validates :content, presence: true
end

app/models/contact.rb
class Contact  
  include ActiveModel::Validations
  include ActiveModel::Conversion

  CONTACT_ATTRIBUTES = [:email, :subject, :message]
  CONTACT_ATTRIBUTES.each do |attr|
    attr_accessor attr
  end

  validates :email, :subject, :message,
  presence: true, allow_blank: false

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def send_message
    ContactMailer.contact_message(self).deliver_now
  end
end

app/models/favorite_producer.rb
class FavoriteProducer < ApplicationRecord
  belongs_to :producer
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :join_table_producer_labels
  has_many :producers, through: :join_table_producer_labels
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :join_table_product_categories
  has_many :categories, through: :join_table_product_category
  has_one_attached :avatar
  has_many_attached :images
  has_many :comments
  
  belongs_to :producer, optional: true
  has_many :favorite_producers  
  has_many :favorited_by, through: :favorite_producers, source: :user  
  has_many :ratings

  geocoded_by :geocode_address
  after_validation :geocode

  validates :phone_number, if: :phone_number_nil?,
  length: { is: 10 },
  format: { with: /\d[0-9]\)*\z/ , message: "doit être au format : 0601020304 (pas d'espace)"}

  validates :first_name, :last_name, if: :names_nil?,
  length: { minimum: 1 }

  def geocode_address
    [address,city_name, zip_code].compact.join(', ')
  end
  
  private

  def phone_number_nil?
    phone_number != nil
  end

  def names_nil?
    first_name != nil
    last_name != nil
  end

  ### Sending an email when a producer is created
  after_create :welcome_send
  def welcome_send
    ProducerMailer.welcome_email(self).deliver_now
  end

  ### sending an email when a producer is deleted
  before_destroy :goodbye_send
  def goodbye_send
    ProducerMailer.goodbye_email(self).deliver_now
  end

  before_destroy :goodbye_send
  def goodbye_send
    ProducerMailer.goodbye_email(self).deliver_now
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :producer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :ratings
  has_one_attached :avatar_user

  has_many :comments
  has_many :favorite_producers
  has_many :favorites, through: :favorite_producers, source: :producer

  validates :phone_number, if: :phone_number_nil?,
    length: { is: 10 },
    format: { with: /\d[0-9]\)*\z/ , message: "doit être au format : 0601020304 (pas d'espace)"}

  validates :first_name, :last_name, if: :names_nil?,
    length: { minimum: 1 }

  private

  def phone_number_nil?
    phone_number != nil
  end

  def names_nil?
    first_name != nil
    last_name != nil
  end


  ### Sending an email when a user is created
  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  # sending an email when a user is deleted
  before_destroy :goodbye_send
  def goodbye_send
    UserMailer.goodbye_email(self).deliver_now
  end

  before_destroy :goodbye_send
  def goodbye_send
    UserMailer.goodbye_email(self).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_current_user_showing?, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      flash[:notice] = 'Vous avez supprimé votre compte utilisateur. A bientôt !'
      redirect_to root_url
    else
      flash[:error] = 'Une erreur est survenue, nous vous invitons à nous contacter directement.'
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])
    avatar_user = params.dig(:user, :avatar_user)
    first_name = params.dig(:user, :first_name)
    last_name = params.dig(:user, :last_name)
    if avatar_user.nil? && first_name.nil?
      flash[:error] = 'Vous ne pouvez pas télécharger une image vide'
      redirect_to user_path(current_user.id)

    elsif @user.update(user_params)
      flash[:notice] = 'Vos informations ont été mises à jour !'
      redirect_to user_path(current_user.id)

    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def is_current_user_showing?
    unless current_user.id.to_s == params[:id].to_s
      flash[:error] = "Vous ne pouvez pas afficher un profil utilisateur qui n'est pas le vôtre !"
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :phone_number, :avatar_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show mb-0" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>



app/views/layouts/_footer.html.erb
<footer id="footer" role="contentinfo" class='col-12 col-sm-10 offset-sm-1'>
  <p class="hr">
    <a href="#" class="gotop js-gotop"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
  </p>
  <div class="container">
    <div class="col-md-12 text-center">
      <p>
        &copy; Tous au Marché ! Tous droits réservés.<br>
        Créé par A.Carrière, N.Hodée & J.Tournerie
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header role="banner" id="fh5co-header" class='navbar-fixed-top'>
  <nav class="navbar navbar-expand-lg navbar-light py-0">

    <%= link_to root_path , { :class => 'navbar-brand bg-transparent border-0' } do %>
      <div>
        <span style="color: green;">Tous</span><span class="green">au</span><span style="color: #ff9900;">marché</span>
      </div>
    <% end %>
    <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle border-0 mr-2" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <i></i>
    </button>

    <div id="navbar" class="collapse navbar-collapse row mx-1">
      <ul class="navbar-nav ml-2">
        <li class='nav-item'>
          <%= link_to root_path, { :'data-nav-section' => 'home', :class => 'nav-link external' } do %>
            <span>Accueil</span>
          <% end %>
        </li>
        <li class='nav-item'>
          <%= link_to producers_path(@producer), { :'data-nav-section' => 'map', :class => 'nav-link external' } do %>
            <span>Carte</span>
          <% end %>
        </li>
        <li class='nav-item'>
          <%= link_to new_contact_path, { :'data-nav-section' => 'contact', :class => 'nav-link external' } do %>
            <span>Contact</span>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class='nav-item'>
            <%= link_to user_path(current_user), { :'data-nav-section' => 'profile-user', :class => 'nav-link external' }  do %>
              <span>Mon profil utilisateur</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to "Déconnexion", destroy_user_session_path, { method: :delete, :class => 'nav-link external' } %>
          </li>
        <% elsif producer_signed_in? %>
          <li class='nav-item'>
            <%= link_to producer_path(current_producer), { :'data-nav-section' => 'profile-producer', :class => 'nav-link external' } do %>
              <span>Mon profil producteur</span>
            <% end %>
          </li>
          <li class='nav-item'>
            <%= link_to "Déconnexion", destroy_producer_session_path, { method: :delete, :class => 'nav-link external' } %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link external nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Connexion/Inscription
            </a>
            <div class="dropdown-menu dropdown-menu-right text-center" style="left: 8px; right: auto;" aria-labelledby="bd-versions">
              <%= link_to "Inscription Utilisateur", new_user_registration_path, class:"dropdown-item nav-link external"%>
              <%= link_to "Connexion Utilisateur", new_user_session_path, class:"dropdown-item nav-link external"%>
              <div class="dropdown-divider green"></div>
              <%= link_to "Inscription Producteur", new_producer_registration_path, class:"dropdown-item nav-link external"%>
              <%= link_to "Connexion Producteur", new_producer_session_path, class:"dropdown-item nav-link external"%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="jpg" href="https://cdn.pixabay.com/photo/2016/10/18/19/24/carrot-1751148_960_720.png">
    <title>Tous Au Marché </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,400italic,700' rel='stylesheet' type='text/css'>

    <!-- CSS & JS Styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Font Awesome -->
   <script src="https://kit.fontawesome.com/b9f969d6d6.js" crossorigin="anonymous"></script>

    <!-- Leaflet -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
    integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
    integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
    crossorigin=""></script>

  </head>

  <body>
    <link rel="stylesheet" type="text/css" href="https://ws1.postescanada-canadapost.ca/css/addresscomplete-2.30.min.css?key=<%= ENV['ADDRESS_COMPLETE_KEY'] %>" />
    <script type="text/javascript" src="https://ws1.postescanada-canadapost.ca/js/addresscomplete-2.30.min.js?key=<%= ENV['ADDRESS_COMPLETE_KEY'] %>"></script>

    <div class="main-container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/bootstrap-mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "application-mailer", media: "all" %>
  </head>
  <body class="bg-light">
    <%= yield %>
  </body>
</html>